/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.soltelec.igrafica.labrado.presion;

import com.soltelec.model.Vehiculos;
import java.awt.Component;
import java.util.HashMap;
import java.util.Map;
import javax.persistence.EntityManager;
import javax.swing.JTextField;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author luisberna
 */
public class Container extends javax.swing.JDialog {

    private HashMap<String, Component> componentMap;
    private int idVehiculo;
    private int hojaPruebasActual;
    private int idPrueba;
    Vehiculos vehiculo = null;
    java.awt.Frame frame;
    int idUsuario;
    boolean ensenianza;
    boolean aplicTaximetro;
    EntityManager em;

    /**
     * Creates new form Container
     *
     * @param frame
     */
    public Container(java.awt.Frame frame, boolean modal, int idVehiculo, int hojaPruebasActual, int idPrueba, int idUsuario, Vehiculos vehiculo, EntityManager em) {
        super(frame, modal);
        initComponents();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(d);
        setResizable(false);
        this.frame = frame;
        createComponentMap();
        initEventosCheck();
        cargarDatosDePrueba();
        this.idVehiculo = idVehiculo;
        this.hojaPruebasActual = hojaPruebasActual;
        this.idPrueba = idPrueba;
        this.vehiculo = vehiculo;
        this.idUsuario = idUsuario;
        this.em = em;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        panelEje1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtEje1Izquierda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEje1Derecha = new javax.swing.JTextField();
        panelEje4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtEje4Izquierda = new javax.swing.JTextField();
        chkEje4Izquierda = new javax.swing.JCheckBox();
        txtEje4IzquierdaInt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEje4Derecha = new javax.swing.JTextField();
        chkEje4Derecha = new javax.swing.JCheckBox();
        txtEje4DerechaInt = new javax.swing.JTextField();
        panelEje2 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtEje2Izquierda = new javax.swing.JTextField();
        chkEje2Izquierda = new javax.swing.JCheckBox();
        txtEje2IzquierdaInt = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtEje2Derecha = new javax.swing.JTextField();
        chkEje2Derecha = new javax.swing.JCheckBox();
        txtEje2DerechaInt = new javax.swing.JTextField();
        panelEje3 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        txtEje3Izquierda = new javax.swing.JTextField();
        chkEje3Izquierda = new javax.swing.JCheckBox();
        txtEje3IzquierdaInt = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtEje3Derecha = new javax.swing.JTextField();
        chkEje3Derecha = new javax.swing.JCheckBox();
        txtEje3DerechaInt = new javax.swing.JTextField();
        panelEje5 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txtEje5Izquierda = new javax.swing.JTextField();
        chkEje5Izquierda = new javax.swing.JCheckBox();
        txtEje5IzquierdaInt = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtEje5Derecha = new javax.swing.JTextField();
        chkEje5Derecha = new javax.swing.JCheckBox();
        txtEje5DerechaInt = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        chkRespuesto1 = new javax.swing.JCheckBox();
        txtRepuesto1 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        chkRespuesto2 = new javax.swing.JCheckBox();
        txtRepuesto2 = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        chkRespuesto3 = new javax.swing.JCheckBox();
        txtRepuesto3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtEje1IzquierdaP = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtEje1DerechaP = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtEje4IzquierdaP = new javax.swing.JTextField();
        chkEje4IzquierdaP = new javax.swing.JCheckBox();
        txtEje4IzquierdaIntP = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtEje4DerechaP = new javax.swing.JTextField();
        chkEje4DerechaP = new javax.swing.JCheckBox();
        txtEje4DerechaIntP = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        txtEje2IzquierdaP = new javax.swing.JTextField();
        chkEje2IzquierdaP = new javax.swing.JCheckBox();
        txtEje2IzquierdaIntP = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtEje2DerechaP = new javax.swing.JTextField();
        chkEje2DerechaP = new javax.swing.JCheckBox();
        txtEje2DerechaIntP = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        txtEje3IzquierdaP = new javax.swing.JTextField();
        chkEje3IzquierdaP = new javax.swing.JCheckBox();
        txtEje3IzquierdaIntP = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtEje3DerechaP = new javax.swing.JTextField();
        chkEje3DerechaP = new javax.swing.JCheckBox();
        txtEje3DerechaIntP = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        txtEje5IzquierdaP = new javax.swing.JTextField();
        chkEje5IzquierdaP = new javax.swing.JCheckBox();
        txtEje5IzquierdaIntP = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtEje5DerechaP = new javax.swing.JTextField();
        chkEje5DerechaP = new javax.swing.JCheckBox();
        txtEje5DerechaIntP = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();
        chkRespuesto1P = new javax.swing.JCheckBox();
        txtRepuesto1P = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        chkRespuesto2P = new javax.swing.JCheckBox();
        txtRepuesto2P = new javax.swing.JTextField();
        jPanel32 = new javax.swing.JPanel();
        chkRespuesto3P = new javax.swing.JCheckBox();
        txtRepuesto3P = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblPesoBruto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setPreferredSize(new java.awt.Dimension(833, 800));

        panelEje1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eje 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        panelEje1.setLayout(new java.awt.GridLayout());

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Izquierda");
        jLabel8.setOpaque(true);
        panelEje1.add(jLabel8);

        txtEje1Izquierda.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtEje1Izquierda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelEje1.add(txtEje1Izquierda);

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Derecha");
        jLabel9.setOpaque(true);
        panelEje1.add(jLabel9);

        txtEje1Derecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelEje1.add(txtEje1Derecha);

        panelEje4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eje 4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        panelEje4.setLayout(new java.awt.GridLayout());

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Izquierda");
        jLabel16.setOpaque(true);
        panelEje4.add(jLabel16);

        txtEje4Izquierda.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtEje4Izquierda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelEje4.add(txtEje4Izquierda);

        chkEje4Izquierda.setText("Interna");
        chkEje4Izquierda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEje4.add(chkEje4Izquierda);

        txtEje4IzquierdaInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje4IzquierdaInt.setEnabled(false);
        panelEje4.add(txtEje4IzquierdaInt);

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Derecha");
        jLabel17.setOpaque(true);
        panelEje4.add(jLabel17);

        txtEje4Derecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelEje4.add(txtEje4Derecha);

        chkEje4Derecha.setText("Interna");
        chkEje4Derecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEje4.add(chkEje4Derecha);

        txtEje4DerechaInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje4DerechaInt.setEnabled(false);
        panelEje4.add(txtEje4DerechaInt);

        panelEje2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eje 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        panelEje2.setLayout(new java.awt.GridLayout());

        jLabel30.setBackground(new java.awt.Color(204, 204, 204));
        jLabel30.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Izquierda");
        jLabel30.setOpaque(true);
        panelEje2.add(jLabel30);

        txtEje2Izquierda.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtEje2Izquierda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelEje2.add(txtEje2Izquierda);

        chkEje2Izquierda.setText("Interna");
        chkEje2Izquierda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEje2.add(chkEje2Izquierda);

        txtEje2IzquierdaInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje2IzquierdaInt.setEnabled(false);
        panelEje2.add(txtEje2IzquierdaInt);

        jLabel31.setBackground(new java.awt.Color(204, 204, 204));
        jLabel31.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Derecha");
        jLabel31.setOpaque(true);
        panelEje2.add(jLabel31);

        txtEje2Derecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelEje2.add(txtEje2Derecha);

        chkEje2Derecha.setText("Interna");
        chkEje2Derecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEje2.add(chkEje2Derecha);

        txtEje2DerechaInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje2DerechaInt.setEnabled(false);
        panelEje2.add(txtEje2DerechaInt);

        panelEje3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eje 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        panelEje3.setLayout(new java.awt.GridLayout());

        jLabel32.setBackground(new java.awt.Color(204, 204, 204));
        jLabel32.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Izquierda");
        jLabel32.setOpaque(true);
        panelEje3.add(jLabel32);

        txtEje3Izquierda.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtEje3Izquierda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelEje3.add(txtEje3Izquierda);

        chkEje3Izquierda.setText("Interna");
        chkEje3Izquierda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEje3.add(chkEje3Izquierda);

        txtEje3IzquierdaInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje3IzquierdaInt.setEnabled(false);
        panelEje3.add(txtEje3IzquierdaInt);

        jLabel33.setBackground(new java.awt.Color(204, 204, 204));
        jLabel33.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Derecha");
        jLabel33.setOpaque(true);
        panelEje3.add(jLabel33);

        txtEje3Derecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelEje3.add(txtEje3Derecha);

        chkEje3Derecha.setText("Interna");
        chkEje3Derecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEje3.add(chkEje3Derecha);

        txtEje3DerechaInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje3DerechaInt.setEnabled(false);
        panelEje3.add(txtEje3DerechaInt);

        panelEje5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eje 5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        panelEje5.setLayout(new java.awt.GridLayout());

        jLabel34.setBackground(new java.awt.Color(204, 204, 204));
        jLabel34.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Izquierda");
        jLabel34.setOpaque(true);
        panelEje5.add(jLabel34);

        txtEje5Izquierda.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtEje5Izquierda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelEje5.add(txtEje5Izquierda);

        chkEje5Izquierda.setText("Interna");
        chkEje5Izquierda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEje5.add(chkEje5Izquierda);

        txtEje5IzquierdaInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje5IzquierdaInt.setEnabled(false);
        panelEje5.add(txtEje5IzquierdaInt);

        jLabel35.setBackground(new java.awt.Color(204, 204, 204));
        jLabel35.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Derecha");
        jLabel35.setOpaque(true);
        panelEje5.add(jLabel35);

        txtEje5Derecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panelEje5.add(txtEje5Derecha);

        chkEje5Derecha.setText("Interna");
        chkEje5Derecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEje5.add(chkEje5Derecha);

        txtEje5DerechaInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje5DerechaInt.setEnabled(false);
        panelEje5.add(txtEje5DerechaInt);

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repuesto 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel23.setLayout(new java.awt.GridLayout());

        chkRespuesto1.setText("Activo");
        chkRespuesto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel23.add(chkRespuesto1);

        txtRepuesto1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtRepuesto1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRepuesto1.setEnabled(false);
        jPanel23.add(txtRepuesto1);

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repuesto 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel24.setLayout(new java.awt.GridLayout());

        chkRespuesto2.setText("Activo");
        chkRespuesto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel24.add(chkRespuesto2);

        txtRepuesto2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtRepuesto2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRepuesto2.setEnabled(false);
        jPanel24.add(txtRepuesto2);

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repuesto 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel25.setLayout(new java.awt.GridLayout());

        chkRespuesto3.setText("Activo");
        chkRespuesto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel25.add(chkRespuesto3);

        txtRepuesto3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtRepuesto3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRepuesto3.setEnabled(false);
        jPanel25.add(txtRepuesto3);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro profundidad de labrado");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(panelEje1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelEje4, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(panelEje2, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(panelEje3, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelEje5, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelEje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(panelEje2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEje3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEje4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelEje5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Labrado", jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(833, 800));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eje 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel11.setLayout(new java.awt.GridLayout());

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Izquierda");
        jLabel18.setOpaque(true);
        jPanel11.add(jLabel18);

        txtEje1IzquierdaP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtEje1IzquierdaP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel11.add(txtEje1IzquierdaP);

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Derecha");
        jLabel19.setOpaque(true);
        jPanel11.add(jLabel19);

        txtEje1DerechaP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel11.add(txtEje1DerechaP);

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eje 4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel26.setLayout(new java.awt.GridLayout());

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Izquierda");
        jLabel20.setOpaque(true);
        jPanel26.add(jLabel20);

        txtEje4IzquierdaP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtEje4IzquierdaP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel26.add(txtEje4IzquierdaP);

        chkEje4IzquierdaP.setText("Interna");
        chkEje4IzquierdaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel26.add(chkEje4IzquierdaP);

        txtEje4IzquierdaIntP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje4IzquierdaIntP.setEnabled(false);
        jPanel26.add(txtEje4IzquierdaIntP);

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Derecha");
        jLabel21.setOpaque(true);
        jPanel26.add(jLabel21);

        txtEje4DerechaP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel26.add(txtEje4DerechaP);

        chkEje4DerechaP.setText("Interna");
        chkEje4DerechaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel26.add(chkEje4DerechaP);

        txtEje4DerechaIntP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje4DerechaIntP.setEnabled(false);
        jPanel26.add(txtEje4DerechaIntP);

        jPanel27.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eje 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel27.setLayout(new java.awt.GridLayout());

        jLabel36.setBackground(new java.awt.Color(204, 204, 204));
        jLabel36.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Izquierda");
        jLabel36.setOpaque(true);
        jPanel27.add(jLabel36);

        txtEje2IzquierdaP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtEje2IzquierdaP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel27.add(txtEje2IzquierdaP);

        chkEje2IzquierdaP.setText("Interna");
        chkEje2IzquierdaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel27.add(chkEje2IzquierdaP);

        txtEje2IzquierdaIntP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje2IzquierdaIntP.setEnabled(false);
        jPanel27.add(txtEje2IzquierdaIntP);

        jLabel37.setBackground(new java.awt.Color(204, 204, 204));
        jLabel37.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Derecha");
        jLabel37.setOpaque(true);
        jPanel27.add(jLabel37);

        txtEje2DerechaP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel27.add(txtEje2DerechaP);

        chkEje2DerechaP.setText("Interna");
        chkEje2DerechaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel27.add(chkEje2DerechaP);

        txtEje2DerechaIntP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje2DerechaIntP.setEnabled(false);
        jPanel27.add(txtEje2DerechaIntP);

        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eje 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel28.setLayout(new java.awt.GridLayout());

        jLabel38.setBackground(new java.awt.Color(204, 204, 204));
        jLabel38.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Izquierda");
        jLabel38.setOpaque(true);
        jPanel28.add(jLabel38);

        txtEje3IzquierdaP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtEje3IzquierdaP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel28.add(txtEje3IzquierdaP);

        chkEje3IzquierdaP.setText("Interna");
        chkEje3IzquierdaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel28.add(chkEje3IzquierdaP);

        txtEje3IzquierdaIntP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje3IzquierdaIntP.setEnabled(false);
        jPanel28.add(txtEje3IzquierdaIntP);

        jLabel39.setBackground(new java.awt.Color(204, 204, 204));
        jLabel39.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Derecha");
        jLabel39.setOpaque(true);
        jPanel28.add(jLabel39);

        txtEje3DerechaP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel28.add(txtEje3DerechaP);

        chkEje3DerechaP.setText("Interna");
        chkEje3DerechaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel28.add(chkEje3DerechaP);

        txtEje3DerechaIntP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje3DerechaIntP.setEnabled(false);
        jPanel28.add(txtEje3DerechaIntP);

        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eje 5", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel29.setLayout(new java.awt.GridLayout());

        jLabel40.setBackground(new java.awt.Color(204, 204, 204));
        jLabel40.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Izquierda");
        jLabel40.setOpaque(true);
        jPanel29.add(jLabel40);

        txtEje5IzquierdaP.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtEje5IzquierdaP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel29.add(txtEje5IzquierdaP);

        chkEje5IzquierdaP.setText("Interna");
        chkEje5IzquierdaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel29.add(chkEje5IzquierdaP);

        txtEje5IzquierdaIntP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje5IzquierdaIntP.setEnabled(false);
        jPanel29.add(txtEje5IzquierdaIntP);

        jLabel41.setBackground(new java.awt.Color(204, 204, 204));
        jLabel41.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Derecha");
        jLabel41.setOpaque(true);
        jPanel29.add(jLabel41);

        txtEje5DerechaP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel29.add(txtEje5DerechaP);

        chkEje5DerechaP.setText("Interna");
        chkEje5DerechaP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel29.add(chkEje5DerechaP);

        txtEje5DerechaIntP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEje5DerechaIntP.setEnabled(false);
        jPanel29.add(txtEje5DerechaIntP);

        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repuesto 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel30.setLayout(new java.awt.GridLayout());

        chkRespuesto1P.setText("Activo");
        chkRespuesto1P.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel30.add(chkRespuesto1P);

        txtRepuesto1P.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtRepuesto1P.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRepuesto1P.setEnabled(false);
        jPanel30.add(txtRepuesto1P);

        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repuesto 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel31.setLayout(new java.awt.GridLayout());

        chkRespuesto2P.setText("Activo");
        chkRespuesto2P.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel31.add(chkRespuesto2P);

        txtRepuesto2P.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtRepuesto2P.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRepuesto2P.setEnabled(false);
        jPanel31.add(txtRepuesto2P);

        jPanel32.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repuesto 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
        jPanel32.setLayout(new java.awt.GridLayout());

        chkRespuesto3P.setText("Activo");
        chkRespuesto3P.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel32.add(chkRespuesto3P);

        txtRepuesto3P.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtRepuesto3P.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRepuesto3P.setEnabled(false);
        jPanel32.add(txtRepuesto3P);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro de presión");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Presión", jPanel4);

        btnSiguiente.setText("SIguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel3.setText("Peso bruto:");
        jLabel3.setOpaque(true);

        lblPesoBruto.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblPesoBruto.setText("900");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesoBruto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblPesoBruto)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        for (Map.Entry<String, Component> entry : componentMap.entrySet()) {
            Object key = entry.getKey();
            Object val = entry.getValue();

        }


    }//GEN-LAST:event_btnSiguienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JCheckBox chkEje2Derecha;
    private javax.swing.JCheckBox chkEje2DerechaP;
    private javax.swing.JCheckBox chkEje2Izquierda;
    private javax.swing.JCheckBox chkEje2IzquierdaP;
    private javax.swing.JCheckBox chkEje3Derecha;
    private javax.swing.JCheckBox chkEje3DerechaP;
    private javax.swing.JCheckBox chkEje3Izquierda;
    private javax.swing.JCheckBox chkEje3IzquierdaP;
    private javax.swing.JCheckBox chkEje4Derecha;
    private javax.swing.JCheckBox chkEje4DerechaP;
    private javax.swing.JCheckBox chkEje4Izquierda;
    private javax.swing.JCheckBox chkEje4IzquierdaP;
    private javax.swing.JCheckBox chkEje5Derecha;
    private javax.swing.JCheckBox chkEje5DerechaP;
    private javax.swing.JCheckBox chkEje5Izquierda;
    private javax.swing.JCheckBox chkEje5IzquierdaP;
    private javax.swing.JCheckBox chkRespuesto1;
    private javax.swing.JCheckBox chkRespuesto1P;
    private javax.swing.JCheckBox chkRespuesto2;
    private javax.swing.JCheckBox chkRespuesto2P;
    private javax.swing.JCheckBox chkRespuesto3;
    private javax.swing.JCheckBox chkRespuesto3P;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblPesoBruto;
    private javax.swing.JPanel panelEje1;
    private javax.swing.JPanel panelEje2;
    private javax.swing.JPanel panelEje3;
    private javax.swing.JPanel panelEje4;
    private javax.swing.JPanel panelEje5;
    private javax.swing.JTextField txtEje1Derecha;
    private javax.swing.JTextField txtEje1DerechaP;
    private javax.swing.JTextField txtEje1Izquierda;
    private javax.swing.JTextField txtEje1IzquierdaP;
    private javax.swing.JTextField txtEje2Derecha;
    private javax.swing.JTextField txtEje2DerechaInt;
    private javax.swing.JTextField txtEje2DerechaIntP;
    private javax.swing.JTextField txtEje2DerechaP;
    private javax.swing.JTextField txtEje2Izquierda;
    private javax.swing.JTextField txtEje2IzquierdaInt;
    private javax.swing.JTextField txtEje2IzquierdaIntP;
    private javax.swing.JTextField txtEje2IzquierdaP;
    private javax.swing.JTextField txtEje3Derecha;
    private javax.swing.JTextField txtEje3DerechaInt;
    private javax.swing.JTextField txtEje3DerechaIntP;
    private javax.swing.JTextField txtEje3DerechaP;
    private javax.swing.JTextField txtEje3Izquierda;
    private javax.swing.JTextField txtEje3IzquierdaInt;
    private javax.swing.JTextField txtEje3IzquierdaIntP;
    private javax.swing.JTextField txtEje3IzquierdaP;
    private javax.swing.JTextField txtEje4Derecha;
    private javax.swing.JTextField txtEje4DerechaInt;
    private javax.swing.JTextField txtEje4DerechaIntP;
    private javax.swing.JTextField txtEje4DerechaP;
    private javax.swing.JTextField txtEje4Izquierda;
    private javax.swing.JTextField txtEje4IzquierdaInt;
    private javax.swing.JTextField txtEje4IzquierdaIntP;
    private javax.swing.JTextField txtEje4IzquierdaP;
    private javax.swing.JTextField txtEje5Derecha;
    private javax.swing.JTextField txtEje5DerechaInt;
    private javax.swing.JTextField txtEje5DerechaIntP;
    private javax.swing.JTextField txtEje5DerechaP;
    private javax.swing.JTextField txtEje5Izquierda;
    private javax.swing.JTextField txtEje5IzquierdaInt;
    private javax.swing.JTextField txtEje5IzquierdaIntP;
    private javax.swing.JTextField txtEje5IzquierdaP;
    private javax.swing.JTextField txtRepuesto1;
    private javax.swing.JTextField txtRepuesto1P;
    private javax.swing.JTextField txtRepuesto2;
    private javax.swing.JTextField txtRepuesto2P;
    private javax.swing.JTextField txtRepuesto3;
    private javax.swing.JTextField txtRepuesto3P;
    // End of variables declaration//GEN-END:variables

    private void initEventosCheck() {

        //Labrado
        chkEje2Izquierda.addItemListener(new ChangeCheckLabrado(txtEje2IzquierdaInt));
        chkEje3Izquierda.addItemListener(new ChangeCheckLabrado(txtEje3IzquierdaInt));
        chkEje4Izquierda.addItemListener(new ChangeCheckLabrado(txtEje4IzquierdaInt));
        chkEje5Izquierda.addItemListener(new ChangeCheckLabrado(txtEje5IzquierdaInt));

        chkEje2Derecha.addItemListener(new ChangeCheckLabrado(txtEje2DerechaInt));
        chkEje3Derecha.addItemListener(new ChangeCheckLabrado(txtEje3DerechaInt));
        chkEje4Derecha.addItemListener(new ChangeCheckLabrado(txtEje4DerechaInt));
        chkEje5Derecha.addItemListener(new ChangeCheckLabrado(txtEje5DerechaInt));

        chkRespuesto1.addItemListener(new ChangeCheckLabrado(txtRepuesto1));
        chkRespuesto2.addItemListener(new ChangeCheckLabrado(txtRepuesto2));
        chkRespuesto3.addItemListener(new ChangeCheckLabrado(txtRepuesto3));

        //Presion
        chkEje2IzquierdaP.addItemListener(new ChangeCheckLabrado(txtEje2IzquierdaIntP));
        chkEje3IzquierdaP.addItemListener(new ChangeCheckLabrado(txtEje3IzquierdaIntP));
        chkEje4IzquierdaP.addItemListener(new ChangeCheckLabrado(txtEje4IzquierdaIntP));
        chkEje5IzquierdaP.addItemListener(new ChangeCheckLabrado(txtEje5IzquierdaIntP));

        chkEje2DerechaP.addItemListener(new ChangeCheckLabrado(txtEje2DerechaIntP));
        chkEje3DerechaP.addItemListener(new ChangeCheckLabrado(txtEje3DerechaIntP));
        chkEje4DerechaP.addItemListener(new ChangeCheckLabrado(txtEje4DerechaIntP));
        chkEje5DerechaP.addItemListener(new ChangeCheckLabrado(txtEje5DerechaIntP));

        chkRespuesto1P.addItemListener(new ChangeCheckLabrado(txtRepuesto1P));
        chkRespuesto2P.addItemListener(new ChangeCheckLabrado(txtRepuesto2P));
        chkRespuesto3P.addItemListener(new ChangeCheckLabrado(txtRepuesto3P));
    }

    private void createComponentMap() {
        componentMap = new HashMap<>();

        //Labrado
        componentMap.put("9004", txtEje1Izquierda);
        componentMap.put("9005", txtEje2Izquierda);
        componentMap.put("9006", txtEje3Izquierda);
        componentMap.put("9007", txtEje4Izquierda);
        componentMap.put("9008", txtEje5Izquierda);

        componentMap.put("9009", txtEje2IzquierdaInt);
        componentMap.put("9010", txtEje3IzquierdaInt);
        componentMap.put("9011", txtEje4IzquierdaInt);
        componentMap.put("9012", txtEje5IzquierdaInt);

        componentMap.put("9013", txtEje1Derecha);
        componentMap.put("9014", txtEje2Derecha);
        componentMap.put("9015", txtEje3Derecha);
        componentMap.put("9016", txtEje4Derecha);
        componentMap.put("9017", txtEje5Derecha);

        componentMap.put("9018", txtEje2DerechaInt);
        componentMap.put("9019", txtEje3DerechaInt);
        componentMap.put("9020", txtEje4DerechaInt);
        componentMap.put("9021", txtEje5DerechaInt);

        //Presion
        componentMap.put("9022", txtEje1IzquierdaP);
        componentMap.put("9023", txtEje2IzquierdaP);
        componentMap.put("9024", txtEje3IzquierdaP);
        componentMap.put("9025", txtEje4IzquierdaP);
        componentMap.put("9026", txtEje5IzquierdaP);

        componentMap.put("9027", txtEje2IzquierdaIntP);
        componentMap.put("9028", txtEje3IzquierdaIntP);
        componentMap.put("9029", txtEje4IzquierdaIntP);
        componentMap.put("9030", txtEje5IzquierdaIntP);

        componentMap.put("9031", txtEje1DerechaP);
        componentMap.put("9032", txtEje2DerechaP);
        componentMap.put("9033", txtEje3DerechaP);
        componentMap.put("9034", txtEje4DerechaP);
        componentMap.put("9035", txtEje5DerechaP);

        componentMap.put("9036", txtEje2DerechaIntP);
        componentMap.put("9037", txtEje3DerechaIntP);
        componentMap.put("9038", txtEje4DerechaIntP);
        componentMap.put("9039", txtEje5DerechaIntP);

        componentMap.put("9040", txtRepuesto1P);
        componentMap.put("9041", txtRepuesto2P);
        componentMap.put("9042", txtRepuesto3P);

        componentMap.put("9043", txtRepuesto1);
        componentMap.put("9044", txtRepuesto2);
        componentMap.put("9045", txtRepuesto3);
    }

    public Component getComponentByName(String name) {
        if (componentMap.containsKey(name)) {
            return (Component) componentMap.get(name);
        } else {
            return null;
        }
    }

    private void cargarDatosDePrueba() {
        for (Map.Entry<String, Component> entry : componentMap.entrySet()) {
            Object key = entry.getKey();
            ((JTextField) entry.getValue()).setText(key.toString());
        }
    }
}
